baseURL = 'https://berlogabob.github.io/soundingdoubts.github.io/'
languageCode = 'en-US'
title = 'Sounding doubts'
theme = "poplar-theme"
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
